; Generated by Auto-GUI 3.0.1
#SingleInstance Force
#NoEnv
SendMode Input
#include %A_ScriptDir%\Functions.ahk
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Font, s9, Segoe UI
Gui Add, Tab3, x0 y-1 w292 h423, About|Script|Stats
Gui Tab, 1
Gui Add, Text, x0 y24 w289 h51 +0x200 +Center, Version 0.0.3.6 with sleek GUI for my sad script
Gui Add, Text, x0 y74 w288 h48 +0x200, A bit inspired from the one from Idle Champions
Gui Add, Text, x1 y120 w285 h33 +0x200, but Custom made in Adventure-3.0.4
Gui Tab, 2
;Gui Add, Text, x2 y30 w120 h23 +0x200, Alchemy with blood?
;Gui Add, CheckBox, x141 y30 w120 h23, CheckBox
;Gui Add, Text, x2 y60 w120 h23 +0x200, Alchemy with dust?
;Gui Add, CheckBox, x141 y60 w120 h23, CheckBox
;Gui Add, Text, x2 y90 w120 h23 +0x200, Alchemy with exotic?
;Gui Add, CheckBox, x141 y90 w120 h23, CheckBox
Gui Add, Button, x3 y364 w80 h23, &START
;Gui Add, Button, x83 y364 w80 h23, &PAUSE
;Gui Add, Button, x162 y364 w80 h23, &STOP
Gui Tab, 3
Gui Add, Text, x-1 y19 w288 h29 +0x200, Nothing here yet till i figure the rest out
Gui Tab

Gui Show, w289 h420, Window
Return

ButtonStart:
ControlFocus,, ahk_exe Firestone.exe
Send {Click 124 81 0}
Sleep, 1000
GetColor()
ClaimCampaign()
Expedition()
Guardian()
Alchemist()
GoFirestone()
FirestoneTest()
GoMap()
MapRedeem()
loop
{loop, 1
{
 ;the loop starts here
 Sleep, 600000 ;wait 10 mins for next check of expeditions(and it will executive again for the upper loops)
 Expedition()
 }
Sleep, 600000 ; wait another 10 mins and goes to make the map checks(and executes three times so 1h)
GoMap()
MapRedeem()
ClaimCampaign()
Guardian()
Alchemist()
GoFirestone()
FirestoneTest()
}
GuiEscape:
GuiClose:
    ExitApp
$F10::ExitApp
